//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int id_Point { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public int id_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
