
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fitnes.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int id_User { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public Nullable<int> id_FAQ { get; set; }

    public Nullable<int> id_Point { get; set; }

    public string Video { get; set; }

    public string Role { get; set; }



    public virtual FQA FQA { get; set; }

    public virtual Point Point { get; set; }

}

}
